import { expect, test } from "bun:test";
import { readFile } from "node:fs/promises";

const header = "// @generated by npm run build:workflow; do not edit independently.\n";
for (const [source, local] of [
	["../packages/pi-durable-workflow-core/index.ts", "./core.ts"],
	["../pi-session-tools/output-budget.ts", "./output-budget.ts"],
]) {
	test(`installed runtime ${local} matches canonical source`, async () => {
		const canonical = await readFile(new URL(source, import.meta.url), "utf8");
		const shipped = await readFile(new URL(local, import.meta.url), "utf8");
		expect(shipped).toBe(header + canonical);
	});
}

test("workflow runtime imports stay within the deployed directory", async () => {
	for (const name of ["index.ts", "context.ts", "core.ts", "output-budget.ts"]) {
		const source = await readFile(new URL(`./${name}`, import.meta.url), "utf8");
		expect(source).not.toMatch(/(?:from\s*|import\s*\()\s*["']\.\.\//);
	}
});
